name: Testing

on:
  push:
    branches:
      - dev
      - main65
  pull_request:
    branches:
      - dev
      - main65
  workflow_dispatch:

env:
  MODULE_NAME: MuckiLogPlugin
  COMPOSER_NAME: muckiware/log-plugin
  TEST_DATABASE_URL: "mysql://root:root@127.0.0.1:3306/db_test"

jobs:
  phpunit:
    strategy:
      fail-fast: false
      matrix:
        shopware-version:
          - '6.5.x'
          - '6.6.x'
    uses: shopware/github-actions/.github/workflows/phpunit.yml@main
    with:
      extensionName: ${{ github.event.repository.name }}
      shopwareVersion: ${{ matrix.shopware-version }}
      uploadCoverage: true
